server:
  port: 8081

# cấu hình EDC (đổi theo môi trường của bạn)
app:
  edc:
    baseUrl: "http://localhost:19193"       # Provider Management base
    consumerBaseUrl: "http://localhost:29193" # Consumer Management base
    managementPath: "/management/v3"
